
//Ethernet IO BASE definition
/*
#define ETH_RESET_O_BASE	0x040021F0
#define ETH_SCK_O_BASE		0x04002200
#define ETH_SI_O_BASE		0x04002210
#define ETH_SO_I_BASE		0x04002220
#define ETH_CLKOUT_I_BASE	0x04002230
#define ETH_INT_I_BASE		0x04002240
#define ETH_CS_O_BASE		0x04002250
#define ETH_WOL_I_BASE		0x04002260
*/

//Set direction function - output
#define SET_RESET_OUTPUT()	IOWR_ALTERA_AVALON_PIO_DIRECTION(ETH_RESET_O_BASE	,ALTERA_AVALON_PIO_DIRECTION_OUTPUT)
#define SET_SCK_OUTPUT()    IOWR_ALTERA_AVALON_PIO_DIRECTION(ETH_SCK_O_BASE		,ALTERA_AVALON_PIO_DIRECTION_OUTPUT)
#define SET_SI_OUTPUT()		IOWR_ALTERA_AVALON_PIO_DIRECTION(ETH_SI_O_BASE		,ALTERA_AVALON_PIO_DIRECTION_OUTPUT)
#define SET_CS_OUTPUT()		IOWR_ALTERA_AVALON_PIO_DIRECTION(ETH_CS_O_BASE		,ALTERA_AVALON_PIO_DIRECTION_OUTPUT)

//Set direction function - input
#define SET_SO_INPUT()	    IOWR_ALTERA_AVALON_PIO_DIRECTION(ETH_SO_I_BASE		,ALTERA_AVALON_PIO_DIRECTION_INPUT)
#define SET_CLKOUT_INPUT()	IOWR_ALTERA_AVALON_PIO_DIRECTION(ETH_CLKOUT_I_BASE	,ALTERA_AVALON_PIO_DIRECTION_INPUT)
#define SET_INT_INPUT()	    IOWR_ALTERA_AVALON_PIO_DIRECTION(ETH_INT_I_BASE		,ALTERA_AVALON_PIO_DIRECTION_INPUT)
#define SET_WOL_INPUT()	    IOWR_ALTERA_AVALON_PIO_DIRECTION(ETH_WOL_I_BASE		,ALTERA_AVALON_PIO_DIRECTION_INPUT)

//IO Set function
#define	SET_ETH_RESET_O(a)	IOWR_ALTERA_AVALON_PIO_DATA(ETH_RESET_O_BASE, a )
#define	SET_ETH_SCK_O(a)	IOWR_ALTERA_AVALON_PIO_DATA(ETH_SCK_O_BASE,   a )
#define	SET_ETH_SI_O(a)	    IOWR_ALTERA_AVALON_PIO_DATA(ETH_SI_O_BASE,    a )
#define	SET_ETH_CS_O(a)		IOWR_ALTERA_AVALON_PIO_DATA(ETH_CS_O_BASE,    a )

//IO Get function
#define	GET_SO_I()	    	IORD_ALTERA_AVALON_PIO_DATA(ETH_SO_I_BASE		)
#define	GET_CLKOUT_I()	    IORD_ALTERA_AVALON_PIO_DATA(ETH_CLKOUT_I_BASE	)
#define	GET_INT_I()	    	IORD_ALTERA_AVALON_PIO_DATA(ETH_INT_I_BASE		)
#define	GET_WOL_I()	    	IORD_ALTERA_AVALON_PIO_DATA(ETH_WOL_I_BASE		)


