
//USB IO BASE definition
/*
#define USB_SCS_O_BASE			0x04002180
#define USB_SDO_I_BASE			0x04002190
#define USB_SDI_O_BASE			0x040021A0
#define USB_SCK_O_BASE			0x040021B0
#define USB_INT_I_BASE			0x040021C0
#define USB_RST_O_BASE			0x040021D0
#define USB_PC_CONNECT_I_BASE	0x040021E0
*/

//IO Set function
#define	SET_USB_SCS_O(a)	IOWR_ALTERA_AVALON_PIO_DATA(USB_SCS_O_BASE, a)
#define	SET_USB_SDI_O(a)	IOWR_ALTERA_AVALON_PIO_DATA(USB_SDI_O_BASE, a)
#define	SET_USB_SCK_O(a)	IOWR_ALTERA_AVALON_PIO_DATA(USB_SCK_O_BASE, a)
#define	SET_USB_RST_O(a)	IOWR_ALTERA_AVALON_PIO_DATA(USB_RST_O_BASE, a)

//IO Get function
#define	GET_SDO_I()	    	IORD_ALTERA_AVALON_PIO_DATA(USB_SDO_I_BASE			)
#define	GET_INT_I()	    	IORD_ALTERA_AVALON_PIO_DATA(USB_INT_I_BASE			)
#define	GET_PC_CONNECT_I()	IORD_ALTERA_AVALON_PIO_DATA(USB_PC_I_BASE			)

