set_location_assignment PIN_13 -to DATA0
set_location_assignment PIN_6 -to ASDO
set_location_assignment PIN_132 -to DB[8]
set_location_assignment PIN_133 -to DB[7]
set_location_assignment PIN_137 -to DB[4]
set_location_assignment PIN_138 -to WR
set_location_assignment PIN_103 -to P103
set_location_assignment PIN_99 -to P99
set_location_assignment PIN_87 -to P87
set_location_assignment PIN_86 -to P86
set_location_assignment PIN_8 -to NCSO
set_location_assignment PIN_98 -to P98
set_location_assignment PIN_101 -to P101
set_location_assignment PIN_12 -to DCLK
set_location_assignment PIN_94 -to DCOM
set_location_assignment PIN_96 -to A2V5
set_location_assignment PIN_97 -to DCOM
set_location_assignment PIN_21 -to DCOM
set_location_assignment PIN_16 -to FTCK
set_location_assignment PIN_15 -to FTDI
set_location_assignment PIN_20 -to FTDO
set_location_assignment PIN_18 -to FTMS
set_location_assignment PIN_7 -to P7
set_location_assignment PIN_31 -to SD_D[0]
set_location_assignment PIN_46 -to SD_DQM[0]
set_location_assignment PIN_65 -to SD_A[9]
set_location_assignment PIN_80 -to SD_A[0]
set_location_assignment PIN_105 -to P105
set_location_assignment PIN_119 -to DB[14]
set_location_assignment PIN_136 -to DB[5]
set_location_assignment PIN_23 -to FPGA_CLK
set_location_assignment PIN_24 -to P24
set_location_assignment PIN_25 -to P25
set_location_assignment PIN_91 -to P91
set_location_assignment PIN_90 -to P90
set_location_assignment PIN_89 -to P89
set_location_assignment PIN_88 -to P88
set_location_assignment PIN_1 -to P1
set_location_assignment PIN_2 -to P2
set_location_assignment PIN_3 -to P3
set_location_assignment PIN_10 -to P10
set_location_assignment PIN_11 -to P11
set_location_assignment PIN_32 -to SD_D[1]
set_location_assignment PIN_33 -to SD_D[2]
set_location_assignment PIN_28 -to P28
set_location_assignment PIN_30 -to LED_FPGA
set_location_assignment PIN_34 -to SD_D[3]
set_location_assignment PIN_43 -to SD_CLK
set_location_assignment PIN_44 -to SD_D[7]
set_location_assignment PIN_38 -to SD_D[4]
set_location_assignment PIN_39 -to SD_D[5]
set_location_assignment PIN_42 -to SD_D[6]
set_location_assignment PIN_49 -to SD_D[15]
set_location_assignment PIN_50 -to SD_D[14]
set_location_assignment PIN_51 -to SD_D[13]
set_location_assignment PIN_52 -to SD_D[12]
set_location_assignment PIN_53 -to SD_D[11]
set_location_assignment PIN_66 -to SD_A[8]
set_location_assignment PIN_67 -to SD_A[7]
set_location_assignment PIN_54 -to SD_D[10]
set_location_assignment PIN_55 -to SD_D[9]
set_location_assignment PIN_58 -to SD_D[8]
set_location_assignment PIN_59 -to SD_DQM[1]
set_location_assignment PIN_60 -to SD_CKE
set_location_assignment PIN_64 -to SD_A[11]
set_location_assignment PIN_68 -to SD_A[6]
set_location_assignment PIN_69 -to SD_A[5]
set_location_assignment PIN_70 -to SD_A[4]
set_location_assignment PIN_71 -to SD_WE
set_location_assignment PIN_72 -to SD_CAS
set_location_assignment PIN_76 -to SD_BA[1]
set_location_assignment PIN_77 -to SD_A[10]
set_location_assignment PIN_73 -to SD_RAS
set_location_assignment PIN_74 -to SD_CS
set_location_assignment PIN_75 -to SD_BA[0]
set_location_assignment PIN_83 -to SD_A[1]
set_location_assignment PIN_84 -to SD_A[2]
set_location_assignment PIN_85 -to SD_A[3]
set_location_assignment PIN_100 -to P100
set_location_assignment PIN_104 -to P104
set_location_assignment PIN_106 -to P106
set_location_assignment PIN_114 -to AB[16]
set_location_assignment PIN_115 -to DB[15]
set_location_assignment PIN_112 -to AB[18]
set_location_assignment PIN_113 -to AB[17]
set_location_assignment PIN_110 -to DB[1]
set_location_assignment PIN_111 -to DB[0]
set_location_assignment PIN_120 -to DB[13]
set_location_assignment PIN_121 -to DB[2]
set_location_assignment PIN_124 -to DB[3]
set_location_assignment PIN_125 -to RD
set_location_assignment PIN_126 -to DB[12]
set_location_assignment PIN_127 -to DB[11]
set_location_assignment PIN_128 -to DB[10]
set_location_assignment PIN_129 -to DB[9]
set_location_assignment PIN_135 -to DB[6]
set_location_assignment PIN_141 -to CS0
set_location_assignment PIN_142 -to ARM_CLK
set_location_assignment PIN_143 -to P143
set_location_assignment PIN_144 -to P144
set_location_assignment PIN_4 -to DCOM
set_location_assignment PIN_19 -to DCOM
set_location_assignment PIN_22 -to DCOM
set_location_assignment PIN_27 -to DCOM
set_location_assignment PIN_41 -to DCOM
set_location_assignment PIN_48 -to DCOM
set_location_assignment PIN_57 -to DCOM
set_location_assignment PIN_63 -to DCOM
set_location_assignment PIN_79 -to DCOM
set_location_assignment PIN_82 -to DCOM
set_location_assignment PIN_95 -to DCOM
set_location_assignment PIN_118 -to DCOM
set_location_assignment PIN_123 -to DCOM
set_location_assignment PIN_131 -to DCOM
set_location_assignment PIN_140 -to DCOM
set_location_assignment PIN_36 -to GNDA1
set_location_assignment PIN_108 -to GNDA2
